version: '3.4'

services:
  project:
    image: project
    build: ./python
    ports:
      - 5000:5000
    tty: true
    privileged: true
    command: /sbin/init 3
  db:
    image: mariadb:10.5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./db:/var/lib/mysql
